services:
  orders-microservice:
    image: visualfxvault-ordersservice
    build:
      context: .
      dockerfile: APILayer/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - USERS_SERVICE_HOST=http://localhost
      - USERS_SERVICE_PORT=5050
      - MONGO_HOST=localhost
      - MONGO_PORT=27017
      - MONGO_DB=VisualFXVault_Orders
    ports:
      - 7000:8080
