services:
  orders-microservice:
    image: visualfxvault-ordersservice
    build:
      context: .
      dockerfile: APILayer/Dockerfile
      args:
        - configuration=Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - USERS_SERVICE_HOST=http://users-microservice
      - USERS_SERVICE_PORT=5000
      - PRODUCTS_SERVICE_HOST=http://products-microservice
      - PRODUCTS_SERVICE_PORT=6000
      - MONGO_HOST=mongodb-container
      - MONGO_PORT=27017
      - MONGO_DB=VisualFXVault_Orders
    ports:
      - 7000:8080
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  mongodb-container:
    image: mongo:latest
    container_name: mongodb-container
    hostname: mongodb-container
    ports:
      - 27017:27017
    volumes:
      - ../docker-compose/mongodb-init:/docker-entrypoint-initdb.d
    networks:
      - visualfxvault-network
    
networks:
  visualfxvault-network:
    driver: bridge
